INSERT INTO member (userName,exist) VALUES ('kitamoto','FALSE');
INSERT INTO member (userName,exist) VALUES ('komaki','FALSE');
INSERT INTO member (userName,exist) VALUES ('ogawa','FALSE');
INSERT INTO member (userName,exist) VALUES ('kurokawa','FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Heart', 1, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 2, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 3, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 4, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 5, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 6, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 7, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 8, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 9, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 10, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 11, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 12, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 13, 'FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Spade', 1, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 2, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 3, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 4, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 5, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 6, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 7, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 8, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 9, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 10, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 11, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 12, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 13, 'FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Club', 1, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 2, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 3, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 4, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 5, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 6, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 7, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 8, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 9, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 10, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 11, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 12, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 13, 'FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Dia', 1, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 2, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 3, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 4, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 5, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 6, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 7, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 8, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 9, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 10, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 11, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 12, 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 13, 'FALSE');
