INSERT INTO member (userName,exist) VALUES ('kitamoto','FALSE');
INSERT INTO member (userName,exist) VALUES ('komaki','FALSE');
INSERT INTO member (userName,exist) VALUES ('ogawa','FALSE');
INSERT INTO member (userName,exist) VALUES ('kurokawa','FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Heart', 'A', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '2', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '3', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '4', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '5', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '6', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '7', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '8', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '9', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', '10', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 'J', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 'Q', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Heart', 'K', 'FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Spade', 'A', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '2', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '3', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '4', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '5', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '6', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '7', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '8', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '9', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', '10', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 'J', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 'Q', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Spade', 'K', 'FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Club', 'A', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '2', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '3', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '4', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '5', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '6', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '7', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '8', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '9', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', '10', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 'J', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 'Q', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Club', 'K', 'FALSE');

INSERT INTO trump (suit, number, place) VALUES ('Dia', 'A', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '2', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '3', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '4', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '5', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '6', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '7', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '8', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '9', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', '10', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 'J', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 'Q', 'FALSE');
INSERT INTO trump (suit, number, place) VALUES ('Dia', 'K', 'FALSE');

INSERT INTO randtrump (id) VALUES (1);
INSERT INTO randtrump (id) VALUES (2);
INSERT INTO randtrump (id) VALUES (3);
INSERT INTO randtrump (id) VALUES (4);
INSERT INTO randtrump (id) VALUES (5);
